# Server configuration
server:
  applicationConnectors:
  - type: http
    port: ${EMAIL_SERVICE_API_PORT:-8443}
  adminConnectors:
  - type: http
    port: ${EMAIL_SERVICE_ADMIN_PORT:-9443}
  requestLog:
    appenders:
      - type: file
        threshold: TRACE
        currentLogFilename: /projects/email-queue-service/assembly/target/service-1.0.0-SNAPSHOT/service-1.0.0-SNAPSHOT/logs/requests.log
        archivedLogFilenamePattern: /projects/email-queue-service/assembly/target/service-1.0.0-SNAPSHOT/service-1.0.0-SNAPSHOT/logs/requests-%d.log
        archive: true
        archivedFileCount: 5
        timeZone: UTC

# Logging configuration
logging:
  level: DEBUG
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: /projects/email-queue-service/assembly/target/service-1.0.0-SNAPSHOT/service-1.0.0-SNAPSHOT/logs/service.log
      archivedLogFilenamePattern: /projects/email-queue-service/assembly/target/service-1.0.0-SNAPSHOT/service-1.0.0-SNAPSHOT/service-%d.log
      archive: true
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{txid}] %logger{35} - %msg%n"
      
# AMQP queue configuration
amqp:
  hostname: ${EMAIL_SERVICE_AMQP_HOST:-localhost}
  port: ${EMAIL_SERVICE_AMQP_PORT:-5672}
  virtualHost: ${EMAIL_SERVICE_AMQP_VHOST}
  username: ${EMAIL_SERVICE_AMQP_USERNAME:-amqpuser}
  password: ${EMAIL_SERVICE_AMQP_PASSWORD:-amqppassword}
  exchange: ${EMAIL_SERVICE_AMQP_EXCHANGE:-amq.direct}
  routingKeys:
    - email
    
# Mail configuraturation
mail:

  # SMTP configuration
  smtp:
    host: ${EMAIL_SERVICE_SMTP_HOST:-localhost}
    port: ${EMAIL_SERVICE_SMTP_PORT:-25}
    username: ${EMAIL_SERVICE_SMTP_USERNAME:-smtpuser}
    password: ${EMAIL_SERVICE_SMTP_PASSWORD:-smtppassword}
    transport: PLAIN
    